// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF8B87F5P2TarfHGWxJNsRRGetHVasuiE',
    appId: '1:1092079816436:web:8717db861e0a43c06098a1',
    messagingSenderId: '1092079816436',
    projectId: 'custom-messenger-all',
    authDomain: 'custom-messenger-all.firebaseapp.com',
    storageBucket: 'custom-messenger-all.appspot.com',
    measurementId: 'G-X4TXFFEVGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHDx2Giyr6rXIOv54bIMioa8Ijiuwx6EU',
    appId: '1:1092079816436:android:f9a818a972cd694f6098a1',
    messagingSenderId: '1092079816436',
    projectId: 'custom-messenger-all',
    storageBucket: 'custom-messenger-all.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm9oWky1R4cTR5VtayljpvvgbAK90Ddrc',
    appId: '1:1092079816436:ios:cb467e84bf3869226098a1',
    messagingSenderId: '1092079816436',
    projectId: 'custom-messenger-all',
    storageBucket: 'custom-messenger-all.appspot.com',
    iosClientId: '1092079816436-ervqted0qlv3ds9dsdv2v3d1egtnobp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.customMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm9oWky1R4cTR5VtayljpvvgbAK90Ddrc',
    appId: '1:1092079816436:ios:cb467e84bf3869226098a1',
    messagingSenderId: '1092079816436',
    projectId: 'custom-messenger-all',
    storageBucket: 'custom-messenger-all.appspot.com',
    iosClientId: '1092079816436-ervqted0qlv3ds9dsdv2v3d1egtnobp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.customMessenger',
  );
}
